In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('bases_para_tratar\\2020.csv', 
                 sep=';', 
                 encoding='UTF-8', 
                 decimal='.', 
                 thousands=',',
                 index_col=0
                 )

In [3]:
df.head()

,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,unidade_fornecimento,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
ano_compra,,,,,,,,,,,,,,,,,,,,,
2020,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2020,19/01/2024,270019,"GLICONATO DE CÁLCIO, DOSAGEM:10%, APRESENTAÇÃO...",AMPOLA,...,10.0,ML,AMPOLA 10.00 ML,04.949.905/0001-63,F CARDOSO E CIA LTDA,01.571.702/0001-98,HALEX ISTAR INDUSTRIA FARMACEUTICA SA,9750,4.500,43875.0
2020,FUNDO MUNICIPAL DE SAUDE - MUNICIPIO DE ALTO P...,MUNICIPAL,08.533.932/0001-01,ALTO PARANA,PR,01/01/2020,13/03/2020,243488,"BOLSA VENTILAÇÃO PULMONAR, MATERIAL:BORRACHA, ...",UNIDADE,...,NaN,NaN,UNIDADE,06.974.929/0001-06,NOROESTE MEDICAMENTOS LTDA,73.856.593/0001-66,"PRATI, DONADUZZI & CIA LTDA",3,6.900,20.7
2020,MUNICIPIO DE AMERICO BRASILIENSE,MUNICIPAL,43.976.166/0001-50,AMERICO BRASILIENSE,SP,01/01/2020,06/10/2020,267567,"CARVEDILOL, DOSAGEM:25 MG",COMPRIMIDO,...,NaN,NaN,COMPRIMIDO,01.140.868/0001-50,CIRURGICA OLIMPIO LTDA,61.150.447/0001-31,LABORATORIOS BALDACCI LTDA EM RECUPERACAO JUDI...,36000,0.155,5580.0
2020,MUNICIPIO DE AMERICO BRASILIENSE,MUNICIPAL,43.976.166/0001-50,AMERICO BRASILIENSE,SP,01/01/2020,06/10/2020,271356,"ALPRAZOLAM, DOSAGEM:1 MG",COMPRIMIDO,...,NaN,NaN,COMPRIMIDO,01.140.868/0001-50,CIRURGICA OLIMPIO LTDA,05.254.971/0001-81,ZYDUS NIKKHO FARMACEUTICA LTDA,240000,0.099,23760.0
2020,MUNICIPIO DE AMERICO BRASILIENSE,MUNICIPAL,43.976.166/0001-50,AMERICO BRASILIENSE,SP,01/01/2020,06/10/2020,267565,"CARVEDILOL, DOSAGEM:6,25 MG",COMPRIMIDO,...,NaN,NaN,COMPRIMIDO,01.140.868/0001-50,CIRURGICA OLIMPIO LTDA,61.150.447/0001-31,LABORATORIOS BALDACCI LTDA EM RECUPERACAO JUDI...,36000,0.086,3096.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 84819 entries, 2020 to 2020
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   nome_instituicao                 84819 non-null  object
 1   esfera                           84819 non-null  object
 2   cnpj_instituicao                 84819 non-null  object
 3   municipio_instituicao            84819 non-null  object
 4   uf                               84819 non-null  object
 5   compra                           84819 non-null  object
 6   insercao                         84819 non-null  object
 7   codigo_br                        84819 non-null  int64
 8   descricao_catmat                 84819 non-null  object
 9   unidade_fornecimento             84813 non-null  object
 10  generico                         37135 non-null  object
 11  anvisa                           37135 non-null  float64
 12  modalidade_compra                84819 non-null  object
 13  tipo_compra                      84819 non-null  object
 14  capacidade                       31382 non-null  float64
 15  unidade_medida                   31382 non-null  object
 16  unidade_fornecimento_capacidade  84813 non-null  object
 17  cnpj_fornecedor                  84819 non-null  object
 18  fornecedor                       84819 non-null  object
 19  cnpj_fabricante                  84819 non-null  object
 20  fabricante                       84819 non-null  object
 21  qtd_itens_comprados              84819 non-null  int64
 22  preco_unitario                   84819 non-null  float64
 23  preco_total                      84819 non-null  float64
dtypes: float64(4), int64(2), object(18)
memory usage: 16.2+ MB

In [5]:
df.isnull().sum()

nome_instituicao                       0
esfera                                 0
cnpj_instituicao                       0
municipio_instituicao                  0
uf                                     0
compra                                 0
insercao                               0
codigo_br                              0
descricao_catmat                       0
unidade_fornecimento                   6
generico                           47684
anvisa                             47684
modalidade_compra                      0
tipo_compra                            0
capacidade                         53437
unidade_medida                     53437
unidade_fornecimento_capacidade        6
cnpj_fornecedor                        0
fornecedor                             0
cnpj_fabricante                        0
fabricante                             0
qtd_itens_comprados                    0
preco_unitario                         0
preco_total                            0
dtype: int64

In [6]:
df["descricao_catmat"]

ano_compra
2020    GLICONATO DE CÁLCIO, DOSAGEM:10%, APRESENTAÇÃO...
2020    BOLSA VENTILAÇÃO PULMONAR, MATERIAL:BORRACHA, ...
2020                            CARVEDILOL, DOSAGEM:25 MG
2020                             ALPRAZOLAM, DOSAGEM:1 MG
2020                          CARVEDILOL, DOSAGEM:6,25 MG
                              ...
2020    HIDROCORTISONA, COMPOSIÇÃO:SAL SUCCINATO SÓDIC...
2020                        CAPTOPRIL, CONCENTRAÇÃO:25 MG
2020                           FLUCONAZOL, DOSAGEM:150 MG
2020    ÁCIDO FÓLICO, DOSAGEM:0,2 MG/ML, USO:SOLUÇÃO O...
2020    LIDOCAÍNA CLORIDRATO, DOSAGEM:2%, APRESENTAÇÃO...
Name: descricao_catmat, Length: 84819, dtype: object

In [ ]:
# isso vai separar a coluna descricao_catmat em uma lista de strings, 
# usando a vírgula como separador, e depois pegar o primeiro elemento dessa lista (índice 0) para criar a nova coluna nome_produto.
# assim podemos fazer uma utilização da nova coluna para a indentificação de se é genérico ou não.
# PS: a coluna ['descricao_catmat'] continua tendo as mesmas informações.

df['nome_produto'] = df['descricao_catmat'].str.split(',').str[0]
df[['nome_produto']]

                         nome_produto
ano_compra
2020              GLICONATO DE CÁLCIO
2020        BOLSA VENTILAÇÃO PULMONAR
2020                       CARVEDILOL
2020                       ALPRAZOLAM
2020                       CARVEDILOL
...                               ...
2020                   HIDROCORTISONA
2020                        CAPTOPRIL
2020                       FLUCONAZOL
2020                     ÁCIDO FÓLICO
2020             LIDOCAÍNA CLORIDRATO

[84819 rows x 1 columns]

In [8]:
print(list(df['nome_produto'].unique()))

['GLICONATO DE CÁLCIO', 'BOLSA VENTILAÇÃO PULMONAR', 'CARVEDILOL', 'ALPRAZOLAM', 'MATERIAL FISIOTERAPIA', 'MANIDIPINO', 'GLIMEPIRIDA', 'APARELHO ULTRASSONOGRAFIA', 'CANDESARTANA', 'CIPROFLOXACINO CLORIDRATO', 'APARELHO ELETROESTIMULADOR NEUROMUSCULAR', 'BUPROPIONA CLORIDRATO', 'METILFENIDATO CLORIDRATO', 'OCRELIZUMABE', 'BIMATOPROSTA', 'DOBUTAMINA CLORIDRATO', 'HIDROCORTISONA', 'SAIS PARA REIDRATAÇÃO ORAL', 'REAGENTE PARA DIAGNÓSTICO CLÍNICO 5', 'SINVASTATINA', 'FENOFIBRATO', 'VALPROATO DE SÓDIO', 'ESTRADIOL', 'CLONAZEPAM', 'SORAFENIBE TOSILATO', 'FORMOTEROL FUMARATO', 'TRIMETAZIDINA DICLORIDRATO', 'BROMAZEPAM', 'DOMPERIDONA', 'NIMODIPINO', 'ATORVASTATINA CÁLCICA', 'ROSUVASTATINA', 'TRASTUZUMABE', 'DILTIAZEM CLORIDRATO', 'DORZOLAMIDA CLORIDRATO', 'SULFAMETOXAZOL', 'MORFINA', 'LEUPRORRELINA ACETATO', 'LACOSAMIDA', 'INDAPAMIDA', 'LENÇOL DESCARTÁVEL USO HOSPITALAR', 'MEMANTINA', 'METFORMINA CLORIDRATO', 'LUVA PARA PROCEDIMENTO NÃO CIRÚRGICO', 'ELTROMBOPAG OLAMINA', 'CLORETO DE SÓDIO', 'TUBO ASPIRAÇÃO', 'TANSULOSINA', 'LUVA CIRÚRGICA', 'PROBIÓTICO', 'UMIDIFICADOR', 'ENOXAPARINA', 'RIVAROXABANA', 'TUBO ENDOTRAQUEAL', 'ALFA-1 ANTITRIPSINA (AAT)', 'MESALAZINA', 'INSULINA', 'MULTIVITAMINAS', 'TRANILCIPROMINA', 'SITAGLIPTINA', 'ROTIGOTINA', 'BRAÇADEIRA', 'FINASTERIDA', 'PREDNISOLONA', 'AGULHA ANESTÉSICA', 'MICOFENOLATO', 'ATADURA', 'LEVONORGESTREL', 'SERINGA LABORATÓRIO', 'NORETISTERONA', 'CETOPROFENO', 'AMOXICILINA', 'CONJUNTO IRRIGAÇÃO E ASPIRAÇÃO', 'AMBROXOL', 'MANGUITO', 'CURATIVO', 'NOREPINEFRINA', 'COLECALCIFEROL', 'TOUCA HOSPITALAR', 'CEFTRIAXONA SÓDICA', 'DIMENIDRINATO', 'CATETER INTRAVENOSO', 'LEVETIRACETAM', 'DIAZEPAM', 'HIPOCLORITO DE SÓDIO', 'SONDA TRATO URINÁRIO', 'HIDRÓXIDO DE ALUMÍNIO', 'DIVALPROATO DE SÓDIO', 'CETOCONAZOL', 'SONDA URETRAL', 'EXTRATO MEDICINAL', 'AZITROMICINA', 'DAPAGLIFLOZINA', 'ALOPURINOL', 'ROFLUMILASTE', 'ALBENDAZOL', 'GENTAMICINA', 'PAZOPANIBE', 'ÁCIDO VALPRÓICO', 'RETINOL', 'MÁSCARA', 'ÓXIDO DE ZINCO', 'IVABRADINA CLORIDRATO', 'ASPIRADOR MANUAL', 'ÁCIDO FÓLICO', 'CARBONATO DE CÁLCIO', 'ÁCIDO ACETILSALICÍLICO', 'DESVENLAFAXINA', 'NISTATINA', 'BIPERIDENO', 'METOCLOPRAMIDA CLORIDRATO', 'FENOTEROL BROMIDRATO', 'TETRACAÍNA CLORIDRATO', 'ATENOLOL', 'DEXTRANA', 'TIOTRÓPIO BROMETO', 'AMPICILINA', 'AMITRIPTILINA CLORIDRATO', 'AMIODARONA', 'LEVOTIROXINA SÓDICA', 'PREGABALINA', 'GLICOSAMINA', 'DEXAMETASONA', 'BICARBONATO DE SÓDIO', 'OXICODONA CLORIDRATO', 'CEFALEXINA', 'VITAMINAS DO COMPLEXO B', 'CARBAMAZEPINA', 'GLICOSE', 'CAPTOPRIL', 'BISOPROLOL FUMARATO', 'FUROSEMIDA', 'FLUCONAZOL', 'FENOBARBITAL SÓDICO', 'ARIPIPRAZOL', 'ESPIRONOLACTONA', 'PERMETRINA', 'ENALAPRIL MALEATO', 'METRONIDAZOL', 'DIGOXINA', 'IBUPROFENO', 'DEXCLORFENIRAMINA MALEATO', 'SULFATO FERROSO', 'OMEPRAZOL', 'CIMETIDINA', 'MEBENDAZOL', 'ÁCIDO TRANEXÂMICO', 'METILDOPA', 'ACETILCISTEÍNA', 'HIDROCLOROTIAZIDA', 'GLIBENCLAMIDA', 'HALOPERIDOL', 'TRAMADOL CLORIDRATO', 'BRIMONIDINA TARTARATO', 'PARACETAMOL', 'ÁGUA DESTILADA', 'PROPRANOLOL CLORIDRATO', 'PROMETAZINA CLORIDRATO', 'LEVOFLOXACINO', 'PROPOFOL', 'PREDNISONA', 'CIPROFIBRATO', 'RANITIDINA CLORIDRATO', 'BENZOATO DE BENZILA', 'ÁCIDO URSODESOXICÓLICO', 'NIFEDIPINO', 'DULOXETINA', 'LEVOMEPROMAZINA', 'PERICIAZINA', 'CINACALCETE', 'RINGER', 'DIPIRONA SÓDICA', 'MICONAZOL NITRATO', 'RISPERIDONA', 'ACICLOVIR', 'AMINOFILINA', 'SECNIDAZOL', 'SALBUTAMOL', 'DISPOSITIVO INTRA-UTERINO (DIU)', 'ANLODIPINO BESILATO', 'ITRACONAZOL', 'MANITOL', 'LOSARTANA POTÁSSICA', 'CICLOSPORINA', 'NORFLOXACINO', 'ALENDRONATO DE SÓDIO', 'BENZILPENICILINA', 'FITOMENADIONA', 'TIBOLONA', 'SIMETICONA', 'NAFAZOLINA', 'TINIDAZOL', 'METOPROLOL', 'TRAZODONA CLORIDRATO', 'ZOLPIDEM', 'ACETAZOLAMIDA', 'TIOPENTAL SÓDICO', 'IVERMECTINA', 'VARFARINA SÓDICA', 'POLIMIXINA B', 'CILOSTAZOL', 'LORATADINA', 'DIOSMINA', 'PROGESTERONA', 'PAROXETINA CLORIDRATO', 'ISOSSORBIDA', 'PIROXICAM', 'PICOSSULFATO SÓDICO', 'NIMESULIDA', 'NEOMICINA', 'MELOXICAM', 'OXCARBAZEPINA', 'LORAZEPAM', 'CITALOPRAM', 'PROPATILNITRATO', 'QUETIAPINA', 'PETROLATO', 'TOPIRAMATO', 'FLUOXETINA', 'TIAMINA', 'LAMOTRIGINA', 'TIORIDAZINA CLORIDRATO', 'HEPARINA SÓDICA', 'CLOBAZAM', 'ÁCIDO ASCÓRBICO', 'CLORTALIDONA', 'ESCOPOLAMINA BUTILBROMETO', 'SULFADIAZINA', 'PROPAFENONA CLORIDRATO', 'VENLAFAXINA', 'DICLOFENACO', 'TIMOLOL', 'COLAGENASE', 'SERTRALINA CLORIDRATO', 'ESTRIOL', 'CLOPIDOGREL', 'PETIDINA CLORIDRATO', 'NORTRIPTILINA CLORIDRATO', 'FENTANILA', 'CIANOCOBALAMINA', 'LEVODOPA', 'BETAMETASONA', 'BROMOPRIDA', 'GABAPENTINA', 'PANTOPRAZOL', 'GLICEROL', 'LIDOCAÍNA CLORIDRATO', 'ONDANSETRONA CLORIDRATO', 'ATROPINA SULFATO', 'DOPAMINA', 'CLINDAMICINA', 'MIDAZOLAM', 'ISOFLURANO', 'DOXAZOSINA MESILATO', 'NITRAZEPAM', 'NITROFURANTOÍNA', 'IPRATRÓPIO BROMETO', 'FOLINATO DE CÁLCIO', 'ALPROSTADIL', 'CLARITROMICINA', 'EPINEFRINA', 'AZATIOPRINA', 'SULFATO DE MAGNÉSIO', 'CLORPROMAZINA', 'PENTOXIFILINA', 'FENITOÍNA SÓDICA', 'CINARIZINA', 'BECLOMETASONA DIPROPIONATO', 'CARBONATO DE LÍTIO', 'CLOMIPRAMINA', 'IMIPRAMINA', 'BUDESONIDA', 'CLORETO DE POTÁSSIO', 'DIFENIDRAMINA CLORIDRATO', 'SUGADOR', 'FRALDA DESCARTÁVEL', 'PASTA PROFILÁTICA', 'BROCA ALTA ROTAÇÃO', 'CONDICIONADOR DENTAL', 'LIMA USO ODONTOLÓGICO', 'CUNHA ODONTOLÓGICA', 'CIMENTO ODONTOLÓGICO', 'ACESSÓRIOS - USO ODONTOLÓGICO', 'INDICADOR QUÍMICO', 'FIO DE SUTURA', 'FLUFENAZINA', 'VITELINATO DE PRATA', 'SELANTE', 'EMPAGLIFLOZINA', 'HIDRALAZINA', 'GEL', 'OCITOCINA', 'BROMEXINA CLORIDRATO', 'ELETRODO USO MÉDICO', 'ÁCIDOS GRAXOS ESSENCIAIS', 'PERMANGANATO DE POTÁSSIO', 'NALOXONA CLORIDRATO', 'OXIBUTININA CLORIDRATO', 'ESCITALOPRAM OXALATO', 'GLICLAZIDA', 'HIDRÓXIDO DE CÁLCIO USO ODONTOLÓGICO', 'FIO RETRATOR GENGIVAL', 'ARTICAÍNA', 'INDICADOR BIOLÓGICO', 'ACEBROFILINA', 'FILME RADIOLÓGICO', 'GAS REFRIGERANTE ODONTOLÓGICO', 'MARCADOR DE INSTRUMENTAL', "PASTA D' ÁGUA", 'NITROPRUSSETO DE SÓDIO', 'SUXAMETÔNIO CLORETO', 'CARVÃO ATIVADO', 'DIMETICONA', 'TERBUTALINA SULFATO', 'ERITROMICINA', 'FIXADOR RADIOLÓGICO', 'COLETOR MATERIAL PÉRFURO-CORTANTE', 'OXACILINA', 'LANSOPRAZOL', 'REVELADOR RADIOLÓGICO', 'ADENOSINA', 'DESLANÓSIDO', 'PARAMONOCLOROFENOL USO ODONTOLÓGICO', 'IODETO DE POTÁSSIO', 'ESTROGÊNIOS CONJUGADOS', 'FLUMAZENIL', 'EVIDENCIADOR DENTAL', 'TIRA ABRASIVA - USO ODONTOLÓGICO', 'CARBONO PARA ARTICULAR USO ODONTOLÓGICO', 'FENILEFRINA CLORIDRATO', 'BROCA BAIXA ROTAÇÃO', 'VERAPAMIL CLORIDRATO', 'MUCOPOLISSACARÍDEO', 'BENZOCAÍNA', 'ETILEFRINA CLORIDRATO', 'MÁSCARA CIRÚRGICA', 'AVENTAL DESCARTÁVEL USO HOSPITALAR', 'CATETER OXIGENOTERAPIA', 'BUPIVACAÍNA CLORIDRATO', 'CEFOTAXIMA SÓDICA', 'ÁLCOOL ETÍLICO', 'TAMPA PROTETORA USO MÉDICO', 'FOSFATO DE SÓDIO', 'MÁSCARA PROTEÇÃO RESP. C/ ANVISA', 'MATERIAL GASOTERAPIA', 'SABONETE', 'CATETER PERIFÉRICO', 'EQUIPO INFUSÃO SANGUÍNEA', 'TUBO ENDOTRAQUEAL ', 'CLOREXIDINA DIGLUCONATO', 'PERÓXIDO DE HIDROGÊNIO (ÁGUA OXIGENADA)', 'ACESSÓRIO PARA RADIOLOGIA', 'ADESIVO DENTAL', 'MEPIVACAÍNA CLORIDRATO', 'MATRIZ ODONTOLÓGICA', 'CONJUNTO OXIGÊNIO MEDICINAL', 'ALGINATO USO ODONTOLÓGICO', 'ESCOVA DE ROBSON USO ODONTOLÓGICO', 'ESPÁTULA ODONTOLÓGICA', 'FLUORETO DE SÓDIO', 'HEMOSTÁTICO ABSORVÍVEL', 'LÂMINA LABORATÓRIO', 'AGULHA ODONTOLÓGICA', 'TUBO LABORATÓRIO', 'MICROPIPETA', 'PONTEIRA LABORATÓRIO', 'CÂMARA CONTAGEM', 'PIPETADOR', 'PIPETA', 'PLACA LABORATÓRIO', 'REAGENTE PARA DIAGNÓSTICO CLÍNICO 7', 'AGULHA HIPODÉRMICA', 'CORANTE', 'TUBO PARA COLETA DE AMOSTRA BIOLÓGICA', 'HIPOCLORITO DE SÓDIO DILUÍDO', 'FORMOCRESOL USO ODONTOLÓGICO', 'PRILOCAÍNA', 'EDTA USO ODONTOLÓGICO', 'PASTA MOLDAGEM', 'VERNIZ DENTÁRIO', 'CRESOL', 'GESSO - USO ODONTOLÓGICO', 'CONE ENDODÔNTICO', 'AMÁLGAMA', 'ESPELHO BUCAL', 'APLICADOR ODONTOLÓGICO', 'ALGODÃO', 'CARIOSTÁTICO USO ODONTOLÓGICO', 'BISTURI DESCARTÁVEL', 'COMPRESSA GAZE', 'AGULHA COLETA SANGUE À VÁCUO', 'REAGENTE ANALÍTICO 4', 'REAGENTE PARA DIAGNÓSTICO CLÍNICO 6', 'ÓLEO DE IMERSÃO', 'AVENTAL HOSPITALAR', 'CIMENTO DE IONÔMERO DE VIDRO', 'ADAPTADOR', 'CERA ODONTOLÓGICA', 'LANCETA', 'SORO', 'SUPORTE LABORATÓRIO', 'SERINGA', 'FRASCO COLETOR', 'BANDAGEM ELÁSTICA', 'ORLISTATE', 'LACTULOSE', 'TESTOSTERONA', 'FLUNARIZINA DICLORIDRATO', 'DABIGATRANA ETEXILATO', 'COLCHICINA', 'UMECLIDÍNIO BROMETO', 'TICLOPIDINA', 'PIRFENIDONA', 'LINAGLIPTINA', 'BENFOTIAMINA', 'CICLOBENZAPRINA CLORIDRATO', 'BAMIFILINA CLORIDRATO', 'CUMARINA', 'MONTELUCASTE SÓDICO', 'PIOGLITAZONA CLORIDRATO', 'LIRAGLUTIDA', 'DONEPEZILA', 'USTEQUINUMABE', 'BELIMUMABE', 'METOTREXATO', 'IODOPOVIDONA (PVPI)', 'BENZINA', 'ALOGLIPTINA', 'EXTENSÃO', 'AGULHA', 'GEL LUBRIFICANTE', 'BERÇO HOSPITALAR', 'BLINATUMOMABE', 'MESA AUXILIAR HOSPITALAR', 'MACA CLÍNICA', 'DIETA ENTERAL', 'FLUORESCEÍNA', 'DIETA INFANTIL', 'RANIBIZUMABE', 'BEVACIZUMABE', 'AFLIBERCEPTE', 'MOBILIÁRIO RADIOLÓGICO', 'MATERIAL P/ ISOLAMENTO DENTAL', 'ESPIRAMICINA', 'ASPARTATO DE MAGNÉSIO', 'DISCO - USO ODONTOLOGIA', 'BACLOFENO', 'DETERGENTE ENZIMÁTICO', 'SULPIRIDA', 'FORMALDEÍDO (FORMOL)', 'DISCO', 'METADONA', 'CLOREXIDINA DIGLICONATO', 'CONJUNTO LABORATÓRIO', 'LOPERAMIDA CLORIDRATO', 'DESSENSIBILIZANTE DENTINÁRIO', 'RESINA ACRÍLICA USO ODONTOLÓGICO', 'HEMOSTÁTICO TÓPICO', 'IODO', 'PADRÃO REFERÊNCIA 1', 'IODOFÓRMIO', 'SERINGA ODONTOLOGICA', 'LÂMINA BISTURI', 'REMOVEDOR USO ODONTOLÓGICO', 'CANETA ALTA ROTAÇÃO', 'ESTANTE TUBO ENSAIO', 'REAGENTE ANALÍTICO 2', 'SOLUÇÃO USO MÉDICO', 'MATERIAL LABORATÓRIO', 'PAPEL PARA IMPRESSÃO - USO HOSPITALAR', 'PORTA BROCA', 'MALHA COMPRESSIVA', 'LAMÍNULA', 'ESCOVA LABORATÓRIO', 'SELEGILINA CLORIDRATO', 'MOMETASONA FUROATO', 'FITA HOSPITALAR', 'PIRIDOXINA', 'MIRTAZAPINA', 'ISOXSUPRINA CLORIDRATO', 'DOXICICLINA', 'TRIMEBUTINA MALEATO', 'TRIANCINOLONA', 'VALSARTANA', 'FLUTICASONA', 'TIAMAZOL', 'SALMETEROL XINAFOATO', 'EFEDRINA', 'AMANTADINA', 'NITROGLICERINA', 'METILERGOMETRINA MALEATO', 'METILPREDNISOLONA', 'SURFACTANTE PULMONAR', 'VANCOMICINA CLORIDRATO', 'CARMELOSE SÓDICA', 'MEROPENEM', 'BRINZOLAMIDA', 'CONTRASTE RADIOLÓGICO', 'ALISQUIRENO HEMIFUMARATO', 'TIGECICLINA', 'DEFLAZACORTE', 'TRAVOPROSTA', 'LATANOPROSTA', 'PIRIMETAMINA', 'CETAMINA CLORIDRATO', 'TERIPARATIDA', 'HIDRÓXIDO DE FERRO III', 'DESMOPRESSINA ACETATO', 'ALVEOLÓTOMO', 'CALCADOR / CONDENSADOR USO ODONTOLÓGICO', 'MEPOLIZUMABE', 'SECUQUINUMABE', 'DESCOLADOR ODONTOLÓGICO', 'CALCITRIOL', 'APIXABANA', 'EQUIPO BOMBA INFUSORA', 'CURETA ODONTOLÓGICA', 'CLONIDINA CLORIDRATO', 'ETONOGESTREL', 'TOBRAMICINA', 'ÁCIDO TRICLOROACÉTICO (TCA)', 'ETOMIDATO', 'CURETA PERIODONTAL', 'ESCAVADOR - USO ODONTOLÓGICO', 'FIBRINOLISINA', 'SONDA ODONTOLÓGICA', 'AFASTADOR ODONTOLÓGICO', 'ORGANIZADOR CLÍNICO USO ODONTOLÓGICO', 'BANDEJA', 'BROQUEIRO', 'PINÇA CIRÚRGICA', 'TESOURA INSTRUMENTAL', 'BRUNIDOR ODONTOLÓGICO', 'PINÇA ODONTOLÓGICA', 'DEXTROCETAMINA', 'IMIPENEM', 'RIVASTIGMINA', 'FLUNITRAZEPAM', 'CEFEPIMA CLORIDRATO', 'CEFTAZIDIMA', 'CABERGOLINA', 'MEDROXIPROGESTERONA ACETATO', 'TENOXICAM', 'CABO ESPELHO BUCAL', 'DEXMEDETOMIDINA CLORIDRATO', 'ESCULPIDOR - ODONTOLÓGICO', 'ALBUMINA HUMANA', 'ALFENTANILA CLORIDRATO', 'PIPERACILINA', 'ATRACÚRIO BESILATO', 'LEVOBUPIVACAÍNA CLORIDRATO', 'SEVOFLURANO', 'CEFAZOLINA SÓDICA', 'IMUNOGLOBULINA HUMANA', 'CLORANFENICOL', 'AMICACINA SULFATO', 'TROPICAMIDA', 'BENZOILMETRONIDAZOL', 'DIACEREÍNA', 'NEOSTIGMINA METILSULFATO', 'SORBITOL', 'BOLSA OSTOMIA', 'TELA CIRÚRGICA', 'CLIPE USO CIRÚRGICO', 'ANFOTERICINA B', 'PRIMIDONA', 'BOSENTANA', 'INFLIXIMABE', 'ETOSSUXIMIDA', 'FLUDROCORTISONA ACETATO', 'MICONAZOL', 'AMBRISENTANA', 'CICLOFOSFAMIDA', 'BEZAFIBRATO', 'CARBOCISTEÍNA', 'TIABENDAZOL', 'DEXPANTENOL', 'PRUCALOPRIDA', 'HIDROQUINONA', 'SUPLEMENTO NUTRICIONAL', 'TIZANIDINA', 'RISEDRONATO SÓDICO', 'VILDAGLIPTINA', 'BETAISTINA DICLORIDRATO', 'TOLTERODINA TARTARATO', 'RACEALFATOCOFEROL', 'MIRABEGRONA', 'RAMIPRIL', 'TIROTROPINA ALFA', 'DISPOSITIVO EXTERNO P/ INCONTINÊNCIA URINÁRIA<div class="desc_material"><span class="desc_item"> COMPONENTES:TUBO PLÁSTICO TRANSPARENTE;ADAPTADOR E COLETOR<br><span class="desc_item"> TIPO USO:DESCARTÁVEL<br><span class="desc_item"> CARACTERÍSTICAS ADICIONAIS:ATÓXICO<br><span class="desc_item"> TAMANHO MÉDIO<br>', 'DISPOSITIVO EXTERNO P/ INCONTINÊNCIA URINÁRIA<div class="desc_material"><span class="desc_item"> COMPONENTES:TUBO PLÁSTICO TRANSPARENTE;ADAPTADOR E COLETOR<br><span class="desc_item"> TIPO USO:DESCARTÁVEL<br><span class="desc_item"> CARACTERÍSTICAS ADICIONAIS:ATÓXICO<br><span class="desc_item"> TAMANHO GRANDE<br>', 'ESPAÇADOR', 'CEFALOTINA SÓDICA', 'SISTEMA FECHADO ASPIRAÇÃO TRAQUEAL', 'OXIMETAZOLINA CLORIDRATO', 'ESOMEPRAZOL', 'BISACODIL', 'CATETER VIAS URINÁRIAS', 'EQUIPO', 'ORNITINA', 'PRAMIPEXOL', 'OTILÔNIO BROMETO', 'ACESSÓRIO BOMBA INSULINA', 'DELTAMETRINA', 'DIENOGESTE', 'FÓRCEPS ODONTOLÓGICO', 'ALAVANCA ODONTOLÓGICA', 'PORTA MATRIZ ODONTOLÓGICO', 'TESOURA', 'PORTA-AGULHA', 'GENFIBROZILA', 'RITUXIMABE', 'PERINDOPRIL', 'BUSPIRONA CLORIDRATO', 'EMBALAGEM P/ ESTERILIZAÇÃO', 'PRASUGREL CLORIDRATO', 'REPELENTE', 'TACROLIMO', 'BOLSA TÉRMICA', 'POLIETILENOGLICOL', 'ESFIGMOMANÔMETRO', 'CLOBETASOL', 'PORTA LÂMINA', 'GLICINATO DE MAGNÉSIO', 'PROTETOR SOLAR', 'FERRO ELEMENTAR', 'IBANDRONATO DE SÓDIO', 'COSMÉTICO', 'MONITOR PORTÁTIL', 'HIDROXIZINA CLORIDRATO', 'ESCADA HOSPITALAR', 'DRENO CIRÚRGICO ', 'EXERCITADOR MUSCULATURA', 'FEXOFENADINA', 'CALCIPOTRIOL', 'OLANZAPINA', 'OMALIZUMABE', 'SOLIFENACINA', 'ÁCIDO TIÓCTICO', 'TEICOPLANINA', 'HIDROXICLOROQUINA SULFATO', 'UREIA', 'PORTA AMÁLGAMA', 'POTE ODONTOLÓGICO', 'RIFAMICINA', 'AMBROXOL CLORIDRATO', 'TIOCONAZOL', 'ROCURÔNIO BROMETO', 'LEVODROPROPIZINA', 'CODEÍNA', '8-HIDROXIQUINOLINA BORATO', 'FENOXIMETILPENICILINA', 'METARAMINOL', 'CADEIRA ODONTOLÓGICA', 'SONDA TRATO DIGESTIVO', 'SONDA', 'CATETER ASPIRAÇÃO TRAQUEAL', 'PROTETOR CUTÂNEO', 'COLETOR DE URINA', 'MISOPROSTOL', 'ALENTUZUMABE', 'PRÓTESE INTRAORAL', 'ESPÉCULO', 'LEFLUNOMIDA', 'ESPÁTULA USO MÉDICO', 'TELMISARTANA', 'HILANO', 'VIMPOCETINA', 'VISMODEGIBE', 'GANCICLOVIR SÓDICO', 'ÁCIDO AMINOCAPRÓICO', 'NAPROXENO', 'CIPROEPTADINA CLORIDRATO', 'CONJUNTO PARA PAPANICOLAU', 'OXÍMETRO USO MÉDICO', 'ENZALUTAMIDA', 'TERMÔMETRO CLÍNICO', 'TUBO HOSPITALAR.', 'ESTETOSCÓPIO', 'ABAIXADOR LÍNGUA', 'PRESERVATIVO MASCULINO', 'MÁSCARA GASOTERAPIA', 'PELÍCULA ADESIVA', 'EXEMESTANO', 'OCTREOTIDA', 'VENETOCLAX', 'EZETIMIBA', 'CREME HIDRATANTE', 'ARTIGO PARA HIGIENE NO LEITO', 'DISPOSITIVO EXTERNO P/ INCONTINÊNCIA URINÁRIA', 'CÂNULA OROFARÍNGEA GUEDEL', 'CLAMP', 'TETRACICLINA', 'CIPROTERONA ACETATO', 'AMNIÓTOMO', 'SONDA NASOGÁSTRICA', 'CONECTOR USO MÉDICO', 'GUIA P/ INTUBAÇÃO TRAQUEAL', 'FIXADOR DE CÂNULA DE TRAQUEOSTOMIA', 'CÂNULA DE TRAQUEOSTOMIA', 'FILTRO VENTILAÇÃO MECÂNICA', 'IMOBILIZADOR (ÓRTESE)', 'RECIPIENTE NUTRIÇÃO ENTERAL', 'TUBO SUPRAGLÓTICO', 'DESINFETANTE', 'ESCOVA DEGERMAÇÃO', 'DETERGENTE SANEANTE', 'SAPATILHA HOSPITALAR', 'COLETOR URINA (CONSULTAR INC 05359)', 'EQUIPAMENTO ODONTOLÓGICO', 'MANTA TÉRMICA', 'DRENO CIRÚRGICO', 'PIRACETAM', 'PILOCARPINA CLORIDRATO', 'IMOBILIZADOR (TALA)', 'CATETER CENTRAL', 'CONJUNTO DRENAGEM TÓRAX', 'ERGOMETRINA MALEATO', 'FRASCO - TIPO ALMOTOLIA', 'EQUIPO ESPECIAL', 'ZOLMITRIPTANA', 'SULFANILAMIDA', 'LISINA', 'CITRATO DE CÁLCIO', 'MACROGOL', 'RALOXIFENO CLORIDRATO', 'AMILORIDA CLORIDRATO', 'ÁCIDO PERACÉTICO', 'GOSSERRELINA ACETATO', 'PEÇAS - EQUIPAMENTO ODONTOLÓGICO', 'CLOZAPINA', 'LARINGOSCÓPIO', 'PORTA-AGULHA INSTRUMENTAL', 'GARROTE', 'ESTESIÔMETRO', 'GLUTARALDEÍDO', 'CURATIVO.', 'SIROLIMO', 'CABO BISTURI', 'FRASCO LABORATÓRIO', 'CAMPO CIRÚRGICO 1', 'SERINGA ', 'ALGODÃO HIDRÓFILO', 'ÉTER DIETÍLICO', 'TORNEIRINHA 1', 'CONJUNTO NEBULIZAÇÃO', 'PLACA ADESIVA P/ TESTE DE CONTATO CUTÂNEO', 'VANDETANIBE', 'DUTASTERIDA', 'REANIMADOR MANUAL', 'DROPROPIZINA', 'HIPROMELOSE', 'BOLSA P/ ACONDICIONAMENTO ÓRGÃOS E ESPÉCIMES', 'COMPRESSA HOSPITALAR', 'PERA USO MÉDICO', 'TELA CIRÚRGICA ', 'CONJUNTO TRICOTOMIA', 'EMBALAGEM PARA ESTERILIZAÇÃO', 'OTOSCÓPIO', 'FILTRO LIMITADOR DE O2', 'VÁLVULA', 'ESCALPE', 'PARAFINA', 'COMPADRE (URINOL)', 'MALHA TUBULAR ORTOPÉDICA', 'PROTETOR CLÍNICO ODONTOLÓGICO', 'DAUNORRUBICINA', 'AGULHA ', 'GEFITINIBE', 'RESINA COMPOSTA', 'FLUVOXAMINA MALEATO', 'LERCANIDIPINO', 'CONJUNTO ACADÊMICO USO ODONTOLÓGICO', 'CANETA BAIXA ROTAÇÃO', 'ÁCIDO FLUORÍDRICO', 'NICOTINA', 'PONTA MONTADA USO ODONTOLÓGICO', 'FIO ORTODÔNTICO', 'CONDENSADOR - USO ODONTOLÓGICO', 'CUBETA LABORATÓRIO', 'DENTE ARTIFICIAL', 'CÂMARA ESCURA REVELAÇÃO RAIO X', 'ESPAÇADOR ENDODÔNTICO', 'NEBULIZADOR', 'CUBA USO HOSPITALAR', 'MOLDEIRA ODONTOLÓGICA', 'ISOLANTE - USO ODONTOLÓGICO', 'GRAMPO USO ODONTOLÓGICO', 'CAIXA INSTRUMENTAL', 'PASTA ABRASIVA', 'PINÇA CIRÚRGICA 1', 'TAÇA DE BORRACHA', 'DESCOLADOR CIRÚRGICO', 'ÁCIDO BÓRICO', 'AGULHA SUTURA', 'MUFLA ODONTOLÓGICA', 'EUGENOL [2-METOXI-4-(2-PROPEN-1-IL)FENOL]', 'ESCOVA ENDOCERVICAL', 'GODIVA - USO ODONTOLÓGICO', 'RÉGUA - USO ODONTOLÓGICO', 'CURSOR ODONTOLÓGICO', 'NITROFURAL', 'ÓRTESE PARA COLUNA VERTEBRAL', 'MATERIAL HOSPITALAR', 'DISPOSITIVO P/ MEDIDAS ANTROPOMÉTRICAS', 'DISPOSITIVO', 'DETECTOR FETAL', 'COMADRE', 'PROTETOR RADIOLÓGICO', 'PAPEL PARA EXAME MÉDICO', 'ARMÁRIO VITRINE', 'COLCHÃO - USO HOSPITALAR', 'TUBO DE LATEX', 'CURATIVO ALGINATO', 'ADESIVO CIRÚRGICO', 'DARIFENACINA', 'TRIPTORRELINA', 'PINÇA ANATÔMICA', 'VIGABATRINA', 'ZUCLOPENTIXOL', 'SUFENTANILA CITRATO', 'REIDRATANTE ORAL', 'FINGOLIMODE CLORIDRATO', 'OSIMERTINIBE', 'CARTELA RADIOGRÁFICA', 'NALTREXONA CLORIDRATO', 'DIAMINO FLUORETO DE PRATA USO ODONTOLÓGICO', 'ESMOLOL CLORIDRATO', 'PAPEL EEG', 'DOXORRUBICINA CLORIDRATO', 'EMBALAGEM LABORATÓRIO', 'GORRO HOSPITALAR', 'PROXIMETACAÍNA CLORIDRATO', 'SAIS MINERAIS', 'ÁCIDO ACÉTICO', 'ADALIMUMABE', 'ALGESTONA ACETOFENIDA', 'ACECLOFENACO', 'DISSULFIRAM', 'AMISSULPRIDA', 'OCLUSOR OFTÁLMICO ', 'AMINAFTONA', 'COLPOSCÓPIO', 'FOCO CIRÚRGICO', 'SOTALOL CLORIDRATO', 'PEMBROLIZUMABE', 'ÁCIDO ZOLEDRÔNICO', 'DULAGLUTIDA', 'EDOXABANA', 'RACECADOTRILA', 'CROMOGLICATO DE SÓDIO', 'XILAZINA CLORIDRATO', 'HIDRÓXIDO DE MAGNÉSIO', 'TROMETAMOL', 'SUNITINIBE', 'CAMPO OPERATÓRIO', 'COLAR CERVICAL', 'HALOTANO', 'PAPAÍNA', 'BOTA DE UNNA', 'VEDOLIZUMABE', 'DESONIDA', 'GESTODENO', 'ORFENADRINA CITRATO', 'DESLORATADINA', 'PROMESTRIENO', 'OLMESARTANA MEDOXOMILA', 'GATIFLOXACINO', 'NITAZOXANIDA', 'FENTICONAZOL NITRATO', 'HIALURONIDASE', 'CELECOXIBE', 'LISINOPRIL', 'DROSPIRENONA', 'CLORPROPAMIDA', 'CEFACLOR MONOIDRATO', 'NEBIVOLOL', 'REAGENTE PARA DIAGNÓSTICO CLÍNICO 3', 'REAGENTE PARA DIAGNÓSTICO CLÍNICO 1', 'IMIQUIMODE', 'VASOPRESSINA', 'DENOSUMABE', 'LOÇÃO HIDRATANTE', 'CEFUROXIMA', 'RILUZOL', 'MOXIFLOXACINO', 'CITRATO DE POTÁSSIO', 'TIOCOLCHICOSÍDEO', 'DESOGESTREL', 'INDACATEROL MALEATO', 'ETORICOXIBE', 'ESTAZOLAM', 'CETOTIFENO', 'ETODOLACO', 'CLOPERASTINA', 'LOXOPROFENO SÓDICO', 'CARISOPRODOL', 'PEÇA PARA ESFIGMOMANÔMETRO', 'ALFADARBEPOETINA', 'INSUMOS QUÍMICOS/BIOLÓGICOS', 'NEGATOSCÓPIO', 'PASTA CONDUTORA', 'TRICLOSANA', 'DOSADOR ORAL', 'BANDA ORTODÔNTICA', 'CAIXA P/ ESTERILIZAÇÃO', 'DISPENSADOR', 'LIMA', 'TAMOXIFENO CITRATO', 'CINZEL CIRÚRGICO', 'ESTOJO INSTRUMENTAL CIRÚRGICO', 'BROCA CIRÚRGICA', 'PERÓXIDO DE BENZOÍLA', 'CUBA', 'COMPRESSOR DE AR ODONTOLÓGICO', 'PROPILTIOURACIL', 'ADAPTADOR LABORATÓRIO', 'FENAZOPIRIDINA', 'ESCINA', 'PIRIDOSTIGMINA BROMETO', 'POLICRESULENO', 'SILDENAFILA', 'OFLOXACINO', 'ÁCIDO MEFENÂMICO', 'CICLOPENTOLATO', 'LEVOCETIRIZINA', 'CLOTRIMAZOL', 'PITAVASTATINA', 'MEIO DE CULTURA', 'REMIFENTANILA CLORIDRATO', 'DOXAZOSINA', 'ENALAPRIL', 'CISATRACÚRIO BESILATO', 'CURATIVO HIDROCOLÓIDE', 'CAIXA LABORATÓRIO', 'TIMOMODULINA', 'AUTOCLAVE', 'MESA CLÍNICA', 'SUPORTE PARA SORO', 'DESFIBRILADOR', 'VENTILADOR ARTIFICIAL ELETRÔNICO', 'MESA REFEIÇÃO', 'BIOMBO HOSPITALAR', 'BANCO GIRATÓRIO', 'ÁCIDO FOSFÓRICO', 'ÁCIDO POLIACRÍLICO (PAA)', 'TORNEIRINHA', 'COLETOR DE RESÍDUOS LÍQUIDOS', 'ACESSÓRIO PARA EQUIPAMENTO MÉDICO', 'COBERTURA', 'CARBÔMER', 'FOCO CLÍNICO', 'SAXAGLIPTINA', 'CODERGOCRINA MESILATO', 'ESTRADIOL<div class="desc_material"><span class="desc_item"> APRESENTAÇÃO:TRATAMENTO HORMONAL BIFÁSICO<br><span class="desc_item"> COMPOSIÇÃO:1ªFASE:ESTRADIOL; 2ªFASE: ESTRADIOL+DIDROGESTERONA<br><span class="desc_item"> CONCENTRAÇÃO:1 MG ; 1 MG + 10 MG<br>', 'AGULHA ACUPUNTURA', 'EXTENSOR INFUSÃO VASCULAR', 'PÁ PARA DESFIBRILADOR', 'INTERFERONA', 'VINORELBINA', 'FLUTAMIDA', 'ETINILESTRAD

A pós indentificar todos os produtos unicos crie uma separção para poder inserir os resultados na tabela Generico aonde diversos produtos não foram classificados

In [9]:
palavras_genericos = [
    'CLORIDRATO', 'SÓDICO', 'MALEATO', 'BESILATO', 'ACETATO', 'FUMARATO',
    'NITRATO', 'BROMETO', 'TARTARATO', 'OLAMINA', 'CÁLCIO', 'MAGNÉSIO',
    'ÁCIDO', 'SULFATO', 'SÓDIO', 'POTÁSSICO', 'CLORETO'
]

In [ ]:
def eh_generico(nome):
    nome = nome.upper()
    
    # se contém palavras típicas de princípio ativo → genérico
    for p in palavras_genericos:
        if p in nome:
            return 'Sim'
    
    # se contém palavras que indicam material/equipamento → não é medicamento
    materiais = ['SERINGA', 'CATETER', 'LUVA', 'TUBO', 'APARELHO', 'MÁSCARA',
                 'EQUIPO', 'FRASCO', 'BROCA', 'AGULHA', 'CURATIVO', 'VENTILADOR',
                 'CÂNULA', 'DRENO', 'BOLSA', 'COMPRESSA', 'ODONTOLÓGICO']
    
    for m in materiais:
        if m in nome:
            return 'Não é medicamento'
    
    # se não caiu em nenhuma regra, assume não genérico
    return 'Não'

df['generico'] = df['nome_produto'].apply(eh_generico) 
# apply() aplica a função eh_generico() em cada elemento da coluna 'nome_produto' e cria uma nova coluna 'generico' com os resultados.

In [11]:
df['generico'].value_counts()

generico
Não                  60712
Sim                  17201
Não é medicamento     6906
Name: count, dtype: int64

In [ ]:
df.info() # para ver se não criou outra coluna com o mesmo nome sem querer

<class 'pandas.core.frame.DataFrame'>
Index: 84819 entries, 2020 to 2020
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   nome_instituicao                 84819 non-null  object
 1   esfera                           84819 non-null  object
 2   cnpj_instituicao                 84819 non-null  object
 3   municipio_instituicao            84819 non-null  object
 4   uf                               84819 non-null  object
 5   compra                           84819 non-null  object
 6   insercao                         84819 non-null  object
 7   codigo_br                        84819 non-null  int64
 8   descricao_catmat                 84819 non-null  object
 9   unidade_fornecimento             84813 non-null  object
 10  generico                         84819 non-null  object
 11  anvisa                           37135 non-null  float64
 12  modalidade_compra                84819 non-null  object
 13  tipo_compra                      84819 non-null  object
 14  capacidade                       31382 non-null  float64
 15  unidade_medida                   31382 non-null  object
 16  unidade_fornecimento_capacidade  84813 non-null  object
 17  cnpj_fornecedor                  84819 non-null  object
 18  fornecedor                       84819 non-null  object
 19  cnpj_fabricante                  84819 non-null  object
 20  fabricante                       84819 non-null  object
 21  qtd_itens_comprados              84819 non-null  int64
 22  preco_unitario                   84819 non-null  float64
 23  preco_total                      84819 non-null  float64
 24  nome_produto                     84819 non-null  object
dtypes: float64(4), int64(2), object(19)
memory usage: 16.8+ MB